name: Examples

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -Sall -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4

      - name: run-ekf
        run: ./build/ekf/main

      - name: run-lqr
        run: ./build/lqr/main

      - name: run-lqr-plot
        run: ./build/lqr_plot/main

      - name: run-pid
        run: ./build/pid/main